'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ACCESS_GROUPS
    Public Property PK_ACCESS_GROUP As Integer
    Public Property NOMBRE_CORTO As String
    Public Property DESCRIPCION As String
    Public Property STATUS As String

    Public Overridable Property PAGES_ACCESS_GROUPS As ICollection(Of PAGES_ACCESS_GROUPS) = New HashSet(Of PAGES_ACCESS_GROUPS)
    Public Overridable Property PAGES_ACCESS_GROUPS1 As ICollection(Of PAGES_ACCESS_GROUPS) = New HashSet(Of PAGES_ACCESS_GROUPS)
    Public Overridable Property USERS As ICollection(Of USERS) = New HashSet(Of USERS)

End Class
