'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAJEROS
    Public Property PkCajero As Integer
    Public Property Nombre As String
    Public Property UserName As String
    Public Property PassWord As String
    Public Property Fk_Usuario As Integer

End Class
