'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAT_BANCOS
    Public Property PK_CAT_BANCO As Integer
    Public Property NOMBRE_CORTO As String
    Public Property DESCRIPCION As String
    Public Property SUCURSAL As String
    Public Property NOMBRE_SUCURSAL As String
    Public Property NOMBRE_EJECUTIVO As String
    Public Property STATUS As String

    Public Overridable Property CTAS_BANCARIAS_EMPRESAS As ICollection(Of CTAS_BANCARIAS_EMPRESAS) = New HashSet(Of CTAS_BANCARIAS_EMPRESAS)
    Public Overridable Property CTAS_BANCARIAS_EMPRESAS1 As ICollection(Of CTAS_BANCARIAS_EMPRESAS) = New HashSet(Of CTAS_BANCARIAS_EMPRESAS)

End Class
