'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAT_MONEDAS
    Public Property PK_CAT_MONEDA As Integer
    Public Property NOMBRE_CORTO As String
    Public Property DESCRIPCION As String
    Public Property SIMBOLO As String
    Public Property STATUS As String

    Public Overridable Property CAT_MONTOS_DISPONIBLES As ICollection(Of CAT_MONTOS_DISPONIBLES) = New HashSet(Of CAT_MONTOS_DISPONIBLES)
    Public Overridable Property CAT_MONTOS_DISPONIBLES1 As ICollection(Of CAT_MONTOS_DISPONIBLES) = New HashSet(Of CAT_MONTOS_DISPONIBLES)

End Class
