'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAT_MOSTRAR_HASTA
    Public Property PK_CAT_MOSTRAR_HASTA As Integer
    Public Property NOMBRE_MOSTRAR As String
    Public Property ROW_NUMBER_IN_QUERY As Nullable(Of Integer)
    Public Property STATUS As Nullable(Of Boolean)

End Class
