'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CLIENTES_USERS
    Public Property PK_CLIENTE_USER As Integer
    Public Property FK_CLIENTE As Nullable(Of Integer)
    Public Property FK_USER As Nullable(Of Integer)

    Public Overridable Property CLIENTES As CLIENTES
    Public Overridable Property CLIENTES1 As CLIENTES
    Public Overridable Property CLIENTES2 As CLIENTES
    Public Overridable Property CLIENTES3 As CLIENTES
    Public Overridable Property CLIENTES4 As CLIENTES
    Public Overridable Property CLIENTES5 As CLIENTES
    Public Overridable Property CLIENTES6 As CLIENTES
    Public Overridable Property CLIENTES7 As CLIENTES
    Public Overridable Property CLIENTES8 As CLIENTES
    Public Overridable Property CLIENTES9 As CLIENTES
    Public Overridable Property CLIENTES10 As CLIENTES
    Public Overridable Property CLIENTES11 As CLIENTES
    Public Overridable Property USERS As USERS
    Public Overridable Property USERS1 As USERS
    Public Overridable Property USERS2 As USERS
    Public Overridable Property USERS3 As USERS
    Public Overridable Property USERS4 As USERS
    Public Overridable Property USERS5 As USERS

End Class
