'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CTAS_BANCARIAS_EMPRESAS
    Public Property PK_CTA_BANCARIA_EMPRESA As Integer
    Public Property FK_EMPRESA As Nullable(Of Integer)
    Public Property FK_CAT_BANCO As Nullable(Of Integer)
    Public Property NUMERO_CTA As String
    Public Property CLABE As String
    Public Property CONVENIO As String
    Public Property REFERENCIA As String
    Public Property STATUS As String
    Public Property TITULAR As String

    Public Overridable Property CAT_BANCOS As CAT_BANCOS
    Public Overridable Property CAT_BANCOS1 As CAT_BANCOS
    Public Overridable Property EMPRESAS As EMPRESAS
    Public Overridable Property EMPRESAS1 As EMPRESAS
    Public Overridable Property PAGOS As ICollection(Of PAGOS) = New HashSet(Of PAGOS)
    Public Overridable Property PAGOS1 As ICollection(Of PAGOS) = New HashSet(Of PAGOS)

End Class
