'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class INTEGRATICKETS
    Public Property ID As Integer
    Public Property TICKET As String
    Public Property STOREDID As String
    Public Property ACCOUNTNO As String

End Class
