'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LLAVES_TRANS_SODESI_PRONTIPAGOS
    Public Property PK_LLAVE_TRANS_SODESI_PRONTIPAGOS As Integer
    Public Property FECHA_REFERENCIAS As Nullable(Of Date)
    Public Property FK_CLIENTE As Nullable(Of Integer)
    Public Property REF_CTE As Nullable(Of Integer)
    Public Property PROCESADA As Nullable(Of Integer)

    Public Overridable Property CLIENTES As CLIENTES
    Public Overridable Property CLIENTES1 As CLIENTES

End Class
