'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class logVentaTransacciones
    Public Property id As Integer
    Public Property FK_CAT_TELEFONIA As Nullable(Of Integer)
    Public Property FK_CAT_SERVICIO As Nullable(Of Integer)
    Public Property servicio As String
    Public Property referencia As String
    Public Property externalid As String
    Public Property fecha As Nullable(Of Date)
    Public Property descripcion As String

End Class
