'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NOTICIAS
    Public Property PK_NOTICIA As Integer
    Public Property Descripcion As String
    Public Property FECHA_INI As Date
    Public Property FECHA_VIGENCIA As Date
    Public Property STATUS As Boolean
    Public Property Anuncio As Nullable(Of Boolean)

    Public Overridable Property NOTICIAS_CLIENTES As ICollection(Of NOTICIAS_CLIENTES) = New HashSet(Of NOTICIAS_CLIENTES)
    Public Overridable Property NOTICIAS_CLIENTES1 As ICollection(Of NOTICIAS_CLIENTES) = New HashSet(Of NOTICIAS_CLIENTES)

End Class
