'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PAGES_USERS
    Public Property PK_PAGE_USER As Integer
    Public Property FK_PAGE As Nullable(Of Integer)
    Public Property FK_USER As Nullable(Of Integer)
    Public Property STATUS As String

    Public Overridable Property PAGES As PAGES
    Public Overridable Property PAGES1 As PAGES
    Public Overridable Property USERS As USERS

End Class
