'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class REGISTRO_RAPIDO
    Public Property PK_REGISTRORAPIDO As Integer
    Public Property NOMBRE As String
    Public Property EMAIL As String
    Public Property GIRO_NEGOCIO As String
    Public Property DIRECCIO_NEGOCIO As String
    Public Property ESTADO As String
    Public Property MUNICIPIO As String
    Public Property CP As String
    Public Property TELEFONO_CASA As String
    Public Property TELEFONO_CELULAR As String
    Public Property TIPO_PERSONA As Byte
    Public Property REQUIEREFACTURA As Boolean
    Public Property NOMBREFACTURA As String
    Public Property DIRECCIONFACTURA As String
    Public Property RFCFACTURA As String
    Public Property TELEFONOFACTURA As String
    Public Property VENDEPORINTERNET As Nullable(Of Boolean)
    Public Property FECHACAMBIO As Nullable(Of Date)
    Public Property CLAVEGENERADA As String
    Public Property YASEACTIVO As Boolean
    Public Property CVEENTUSUARIO As Nullable(Of Integer)

End Class
