'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USERS
    Public Property PK_USER As Integer
    Public Property AP_PATERNO As String
    Public Property AP_MATERNO As String
    Public Property NOMBRE As String
    Public Property STATUS As String
    Public Property EMAIL As String
    Public Property USERNAME As String
    Public Property PASSWORD As String
    Public Property FK_ACCESS_GROUP As Nullable(Of Integer)
    Public Property bloqueado As String
    Public Property iswcfuser As Nullable(Of Boolean)
    Public Property usrconsulta As String
    Public Property pwdconsulta As String
    Public Property CODIGO As Nullable(Of Integer)
    Public Property TELEFONO As String

    Public Overridable Property ACCESOS As ICollection(Of ACCESOS) = New HashSet(Of ACCESOS)
    Public Overridable Property ACCESS_GROUPS As ACCESS_GROUPS
    Public Overridable Property CLIENTES_USERS As ICollection(Of CLIENTES_USERS) = New HashSet(Of CLIENTES_USERS)
    Public Overridable Property CLIENTES_USERS1 As ICollection(Of CLIENTES_USERS) = New HashSet(Of CLIENTES_USERS)
    Public Overridable Property CLIENTES_USERS2 As ICollection(Of CLIENTES_USERS) = New HashSet(Of CLIENTES_USERS)
    Public Overridable Property CLIENTES_USERS3 As ICollection(Of CLIENTES_USERS) = New HashSet(Of CLIENTES_USERS)
    Public Overridable Property CLIENTES_USERS4 As ICollection(Of CLIENTES_USERS) = New HashSet(Of CLIENTES_USERS)
    Public Overridable Property CLIENTES_USERS5 As ICollection(Of CLIENTES_USERS) = New HashSet(Of CLIENTES_USERS)
    Public Overridable Property DUDAS_COMENTARIOS As ICollection(Of DUDAS_COMENTARIOS) = New HashSet(Of DUDAS_COMENTARIOS)
    Public Overridable Property PAGES_USERS As ICollection(Of PAGES_USERS) = New HashSet(Of PAGES_USERS)
    Public Overridable Property PAGOS As ICollection(Of PAGOS) = New HashSet(Of PAGOS)
    Public Overridable Property SALDOS As ICollection(Of SALDOS) = New HashSet(Of SALDOS)
    Public Overridable Property TRANSACCIONES As ICollection(Of TRANSACCIONES) = New HashSet(Of TRANSACCIONES)

End Class
