'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ProcomServiceRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BalanceResult", [Namespace]:="http://model.tae.com.mx"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BalanceResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private balanceField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property balance() As Double
            Get
                Return Me.balanceField
            End Get
            Set
                If (Me.balanceField.Equals(value) <> true) Then
                    Me.balanceField = value
                    Me.RaisePropertyChanged("balance")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceException", [Namespace]:="http://rpc.xml.javax"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ServiceException
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private linkedCauseField As ProcomServiceRef.Throwable
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property linkedCause() As ProcomServiceRef.Throwable
            Get
                Return Me.linkedCauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.linkedCauseField, value) <> true) Then
                    Me.linkedCauseField = value
                    Me.RaisePropertyChanged("linkedCause")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Throwable", [Namespace]:="http://lang.java"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Throwable
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TransactionResult", [Namespace]:="http://model.tae.com.mx"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TransactionResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private autorizacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private carrierField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private codigoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fechaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idTransactionField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private montoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private respuestaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usuarioField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property autorizacion() As String
            Get
                Return Me.autorizacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.autorizacionField, value) <> true) Then
                    Me.autorizacionField = value
                    Me.RaisePropertyChanged("autorizacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property carrier() As String
            Get
                Return Me.carrierField
            End Get
            Set
                If (Object.ReferenceEquals(Me.carrierField, value) <> true) Then
                    Me.carrierField = value
                    Me.RaisePropertyChanged("carrier")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codigoField, value) <> true) Then
                    Me.codigoField = value
                    Me.RaisePropertyChanged("codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descripcionField, value) <> true) Then
                    Me.descripcionField = value
                    Me.RaisePropertyChanged("descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fechaField, value) <> true) Then
                    Me.fechaField = value
                    Me.RaisePropertyChanged("fecha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property idTransaction() As Long
            Get
                Return Me.idTransactionField
            End Get
            Set
                If (Me.idTransactionField.Equals(value) <> true) Then
                    Me.idTransactionField = value
                    Me.RaisePropertyChanged("idTransaction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property monto() As Integer
            Get
                Return Me.montoField
            End Get
            Set
                If (Me.montoField.Equals(value) <> true) Then
                    Me.montoField = value
                    Me.RaisePropertyChanged("monto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.numeroField, value) <> true) Then
                    Me.numeroField = value
                    Me.RaisePropertyChanged("numero")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property respuesta() As String
            Get
                Return Me.respuestaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.respuestaField, value) <> true) Then
                    Me.respuestaField = value
                    Me.RaisePropertyChanged("respuesta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.usuarioField, value) <> true) Then
                    Me.usuarioField = value
                    Me.RaisePropertyChanged("usuario")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AccountResult", [Namespace]:="http://model.tae.com.mx"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AccountResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private beneficiarioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private comentarioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idCuentaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nombreBancoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroCuentaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private requiereFichaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private sucursalField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property beneficiario() As String
            Get
                Return Me.beneficiarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.beneficiarioField, value) <> true) Then
                    Me.beneficiarioField = value
                    Me.RaisePropertyChanged("beneficiario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property comentario() As String
            Get
                Return Me.comentarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.comentarioField, value) <> true) Then
                    Me.comentarioField = value
                    Me.RaisePropertyChanged("comentario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property idCuenta() As Integer
            Get
                Return Me.idCuentaField
            End Get
            Set
                If (Me.idCuentaField.Equals(value) <> true) Then
                    Me.idCuentaField = value
                    Me.RaisePropertyChanged("idCuenta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nombreBanco() As String
            Get
                Return Me.nombreBancoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nombreBancoField, value) <> true) Then
                    Me.nombreBancoField = value
                    Me.RaisePropertyChanged("nombreBanco")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroCuenta() As String
            Get
                Return Me.numeroCuentaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.numeroCuentaField, value) <> true) Then
                    Me.numeroCuentaField = value
                    Me.RaisePropertyChanged("numeroCuenta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property requiereFicha() As String
            Get
                Return Me.requiereFichaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.requiereFichaField, value) <> true) Then
                    Me.requiereFichaField = value
                    Me.RaisePropertyChanged("requiereFicha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property sucursal() As String
            Get
                Return Me.sucursalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.sucursalField, value) <> true) Then
                    Me.sucursalField = value
                    Me.RaisePropertyChanged("sucursal")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="IOException", [Namespace]:="http://io.java"),  _
     System.SerializableAttribute()>  _
    Partial Public Class IOException
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RecargaResult", [Namespace]:="http://model.taepue.com.mx"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RecargaResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private codigoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descripcionResultadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private folioExternoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private folioTaePueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private transaccionExternaField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codigoField, value) <> true) Then
                    Me.codigoField = value
                    Me.RaisePropertyChanged("codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property descripcionResultado() As String
            Get
                Return Me.descripcionResultadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descripcionResultadoField, value) <> true) Then
                    Me.descripcionResultadoField = value
                    Me.RaisePropertyChanged("descripcionResultado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property folioExterno() As String
            Get
                Return Me.folioExternoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.folioExternoField, value) <> true) Then
                    Me.folioExternoField = value
                    Me.RaisePropertyChanged("folioExterno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property folioTaePue() As String
            Get
                Return Me.folioTaePueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.folioTaePueField, value) <> true) Then
                    Me.folioTaePueField = value
                    Me.RaisePropertyChanged("folioTaePue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property transaccionExterna() As String
            Get
                Return Me.transaccionExternaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.transaccionExternaField, value) <> true) Then
                    Me.transaccionExternaField = value
                    Me.RaisePropertyChanged("transaccionExterna")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceResult", [Namespace]:="http://model.tae.com.mx"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ServiceResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private succesfulField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property succesful() As Integer
            Get
                Return Me.succesfulField
            End Get
            Set
                If (Me.succesfulField.Equals(value) <> true) Then
                    Me.succesfulField = value
                    Me.RaisePropertyChanged("succesful")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Deposit", [Namespace]:="http://model.tae.com.mx"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Deposit
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private archivoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private autorizacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fechaFichaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private horaFichaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idCuentaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private montoField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property archivo() As String
            Get
                Return Me.archivoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.archivoField, value) <> true) Then
                    Me.archivoField = value
                    Me.RaisePropertyChanged("archivo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property autorizacion() As String
            Get
                Return Me.autorizacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.autorizacionField, value) <> true) Then
                    Me.autorizacionField = value
                    Me.RaisePropertyChanged("autorizacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property fechaFicha() As String
            Get
                Return Me.fechaFichaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fechaFichaField, value) <> true) Then
                    Me.fechaFichaField = value
                    Me.RaisePropertyChanged("fechaFicha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property horaFicha() As String
            Get
                Return Me.horaFichaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.horaFichaField, value) <> true) Then
                    Me.horaFichaField = value
                    Me.RaisePropertyChanged("horaFicha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property idCuenta() As Integer
            Get
                Return Me.idCuentaField
            End Get
            Set
                If (Me.idCuentaField.Equals(value) <> true) Then
                    Me.idCuentaField = value
                    Me.RaisePropertyChanged("idCuenta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property monto() As Double
            Get
                Return Me.montoField
            End Get
            Set
                If (Me.montoField.Equals(value) <> true) Then
                    Me.montoField = value
                    Me.RaisePropertyChanged("monto")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DepositResult", [Namespace]:="http://model.tae.com.mx"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DepositResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private exitoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fechaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private horaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idDepositoField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property exito() As Integer
            Get
                Return Me.exitoField
            End Get
            Set
                If (Me.exitoField.Equals(value) <> true) Then
                    Me.exitoField = value
                    Me.RaisePropertyChanged("exito")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fechaField, value) <> true) Then
                    Me.fechaField = value
                    Me.RaisePropertyChanged("fecha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property hora() As String
            Get
                Return Me.horaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.horaField, value) <> true) Then
                    Me.horaField = value
                    Me.RaisePropertyChanged("hora")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property idDeposito() As Integer
            Get
                Return Me.idDepositoField
            End Get
            Set
                If (Me.idDepositoField.Equals(value) <> true) Then
                    Me.idDepositoField = value
                    Me.RaisePropertyChanged("idDeposito")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://services.tae.com.mx", ConfigurationName:="ProcomServiceRef.posPortType")>  _
    Public Interface posPortType
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ProcomServiceRef.ServiceException), Action:="", Name:="ServiceException")>  _
        Function getBalance(ByVal in0 As String, ByVal in1 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> ProcomServiceRef.BalanceResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getBalanceAsync(ByVal in0 As String, ByVal in1 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> System.Threading.Tasks.Task(Of ProcomServiceRef.BalanceResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ProcomServiceRef.ServiceException), Action:="", Name:="ServiceException")>  _
        Function getTransactions(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> ProcomServiceRef.TransactionResult()
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getTransactionsAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> System.Threading.Tasks.Task(Of ProcomServiceRef.TransactionResult())
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ProcomServiceRef.IOException), Action:="", Name:="IOException"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ProcomServiceRef.ServiceException), Action:="", Name:="ServiceException")>  _
        Function getAccounts(ByVal in0 As String, ByVal in1 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> ProcomServiceRef.AccountResult()
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getAccountsAsync(ByVal in0 As String, ByVal in1 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> System.Threading.Tasks.Task(Of ProcomServiceRef.AccountResult())
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function doTransaction(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As Integer, ByVal in4 As Double, ByVal in5 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> ProcomServiceRef.RecargaResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function doTransactionAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As Integer, ByVal in4 As Double, ByVal in5 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> System.Threading.Tasks.Task(Of ProcomServiceRef.RecargaResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function doPosTransaction(ByVal in0 As String, ByVal in1 As String, ByVal in2 As Long, ByVal in3 As String, ByVal in4 As Integer, ByVal in5 As Double, ByVal in6 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> ProcomServiceRef.RecargaResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function doPosTransactionAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As Long, ByVal in3 As String, ByVal in4 As Integer, ByVal in5 As Double, ByVal in6 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> System.Threading.Tasks.Task(Of ProcomServiceRef.RecargaResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ProcomServiceRef.ServiceException), Action:="", Name:="ServiceException")>  _
        Function setNewPassphrase(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> ProcomServiceRef.ServiceResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function setNewPassphraseAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> System.Threading.Tasks.Task(Of ProcomServiceRef.ServiceResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ProcomServiceRef.IOException), Action:="", Name:="IOException"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ProcomServiceRef.ServiceException), Action:="", Name:="ServiceException")>  _
        Function notifyDeposit(ByVal in0 As String, ByVal in1 As String, ByVal in2 As ProcomServiceRef.Deposit) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> ProcomServiceRef.DepositResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function notifyDepositAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As ProcomServiceRef.Deposit) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> System.Threading.Tasks.Task(Of ProcomServiceRef.DepositResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getPosTransaction(ByVal in0 As String, ByVal in1 As String, ByVal in2 As Long) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> ProcomServiceRef.RecargaResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getPosTransactionAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As Long) As <System.ServiceModel.MessageParameterAttribute(Name:="out")> System.Threading.Tasks.Task(Of ProcomServiceRef.RecargaResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface posPortTypeChannel
        Inherits ProcomServiceRef.posPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class posPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of ProcomServiceRef.posPortType)
        Implements ProcomServiceRef.posPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getBalance(ByVal in0 As String, ByVal in1 As String) As ProcomServiceRef.BalanceResult Implements ProcomServiceRef.posPortType.getBalance
            Return MyBase.Channel.getBalance(in0, in1)
        End Function
        
        Public Function getBalanceAsync(ByVal in0 As String, ByVal in1 As String) As System.Threading.Tasks.Task(Of ProcomServiceRef.BalanceResult) Implements ProcomServiceRef.posPortType.getBalanceAsync
            Return MyBase.Channel.getBalanceAsync(in0, in1)
        End Function
        
        Public Function getTransactions(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String) As ProcomServiceRef.TransactionResult() Implements ProcomServiceRef.posPortType.getTransactions
            Return MyBase.Channel.getTransactions(in0, in1, in2)
        End Function
        
        Public Function getTransactionsAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String) As System.Threading.Tasks.Task(Of ProcomServiceRef.TransactionResult()) Implements ProcomServiceRef.posPortType.getTransactionsAsync
            Return MyBase.Channel.getTransactionsAsync(in0, in1, in2)
        End Function
        
        Public Function getAccounts(ByVal in0 As String, ByVal in1 As String) As ProcomServiceRef.AccountResult() Implements ProcomServiceRef.posPortType.getAccounts
            Return MyBase.Channel.getAccounts(in0, in1)
        End Function
        
        Public Function getAccountsAsync(ByVal in0 As String, ByVal in1 As String) As System.Threading.Tasks.Task(Of ProcomServiceRef.AccountResult()) Implements ProcomServiceRef.posPortType.getAccountsAsync
            Return MyBase.Channel.getAccountsAsync(in0, in1)
        End Function
        
        Public Function doTransaction(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As Integer, ByVal in4 As Double, ByVal in5 As String) As ProcomServiceRef.RecargaResult Implements ProcomServiceRef.posPortType.doTransaction
            Return MyBase.Channel.doTransaction(in0, in1, in2, in3, in4, in5)
        End Function
        
        Public Function doTransactionAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As Integer, ByVal in4 As Double, ByVal in5 As String) As System.Threading.Tasks.Task(Of ProcomServiceRef.RecargaResult) Implements ProcomServiceRef.posPortType.doTransactionAsync
            Return MyBase.Channel.doTransactionAsync(in0, in1, in2, in3, in4, in5)
        End Function
        
        Public Function doPosTransaction(ByVal in0 As String, ByVal in1 As String, ByVal in2 As Long, ByVal in3 As String, ByVal in4 As Integer, ByVal in5 As Double, ByVal in6 As String) As ProcomServiceRef.RecargaResult Implements ProcomServiceRef.posPortType.doPosTransaction
            Return MyBase.Channel.doPosTransaction(in0, in1, in2, in3, in4, in5, in6)
        End Function
        
        Public Function doPosTransactionAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As Long, ByVal in3 As String, ByVal in4 As Integer, ByVal in5 As Double, ByVal in6 As String) As System.Threading.Tasks.Task(Of ProcomServiceRef.RecargaResult) Implements ProcomServiceRef.posPortType.doPosTransactionAsync
            Return MyBase.Channel.doPosTransactionAsync(in0, in1, in2, in3, in4, in5, in6)
        End Function
        
        Public Function setNewPassphrase(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String) As ProcomServiceRef.ServiceResult Implements ProcomServiceRef.posPortType.setNewPassphrase
            Return MyBase.Channel.setNewPassphrase(in0, in1, in2)
        End Function
        
        Public Function setNewPassphraseAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String) As System.Threading.Tasks.Task(Of ProcomServiceRef.ServiceResult) Implements ProcomServiceRef.posPortType.setNewPassphraseAsync
            Return MyBase.Channel.setNewPassphraseAsync(in0, in1, in2)
        End Function
        
        Public Function notifyDeposit(ByVal in0 As String, ByVal in1 As String, ByVal in2 As ProcomServiceRef.Deposit) As ProcomServiceRef.DepositResult Implements ProcomServiceRef.posPortType.notifyDeposit
            Return MyBase.Channel.notifyDeposit(in0, in1, in2)
        End Function
        
        Public Function notifyDepositAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As ProcomServiceRef.Deposit) As System.Threading.Tasks.Task(Of ProcomServiceRef.DepositResult) Implements ProcomServiceRef.posPortType.notifyDepositAsync
            Return MyBase.Channel.notifyDepositAsync(in0, in1, in2)
        End Function
        
        Public Function getPosTransaction(ByVal in0 As String, ByVal in1 As String, ByVal in2 As Long) As ProcomServiceRef.RecargaResult Implements ProcomServiceRef.posPortType.getPosTransaction
            Return MyBase.Channel.getPosTransaction(in0, in1, in2)
        End Function
        
        Public Function getPosTransactionAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As Long) As System.Threading.Tasks.Task(Of ProcomServiceRef.RecargaResult) Implements ProcomServiceRef.posPortType.getPosTransactionAsync
            Return MyBase.Channel.getPosTransactionAsync(in0, in1, in2)
        End Function
    End Class
End Namespace
