'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace net.itmultiwebservice.www
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Recargas_ElectronicasSoap", [Namespace]:="DMM")>  _
    Partial Public Class Recargas_Electronicas
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private atencionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private depositosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private moviajOperationCompleted As System.Threading.SendOrPostCallback
        
        Private movidjOperationCompleted As System.Threading.SendOrPostCallback
        
        Private msncOperationCompleted As System.Threading.SendOrPostCallback
        
        Private msnldoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private msnOperationCompleted As System.Threading.SendOrPostCallback
        
        Private movidrjOperationCompleted As System.Threading.SendOrPostCallback
        
        Private saldojOperationCompleted As System.Threading.SendOrPostCallback
        
        Private javaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private gprstaeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private gprsautOperationCompleted As System.Threading.SendOrPostCallback
        
        Private movijOperationCompleted As System.Threading.SendOrPostCallback
        
        Private plugtaeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TAEOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TAESALDOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BACK_CODE.My.MySettings.Default.BACK_CODE_net_itmultiwebservice_www_Recargas_Electronicas
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event atencionCompleted As atencionCompletedEventHandler
        
        '''<remarks/>
        Public Event depositosCompleted As depositosCompletedEventHandler
        
        '''<remarks/>
        Public Event moviajCompleted As moviajCompletedEventHandler
        
        '''<remarks/>
        Public Event movidjCompleted As movidjCompletedEventHandler
        
        '''<remarks/>
        Public Event msncCompleted As msncCompletedEventHandler
        
        '''<remarks/>
        Public Event msnldoCompleted As msnldoCompletedEventHandler
        
        '''<remarks/>
        Public Event msnCompleted As msnCompletedEventHandler
        
        '''<remarks/>
        Public Event movidrjCompleted As movidrjCompletedEventHandler
        
        '''<remarks/>
        Public Event saldojCompleted As saldojCompletedEventHandler
        
        '''<remarks/>
        Public Event javaCompleted As javaCompletedEventHandler
        
        '''<remarks/>
        Public Event gprstaeCompleted As gprstaeCompletedEventHandler
        
        '''<remarks/>
        Public Event gprsautCompleted As gprsautCompletedEventHandler
        
        '''<remarks/>
        Public Event movijCompleted As movijCompletedEventHandler
        
        '''<remarks/>
        Public Event plugtaeCompleted As plugtaeCompletedEventHandler
        
        '''<remarks/>
        Public Event TAECompleted As TAECompletedEventHandler
        
        '''<remarks/>
        Public Event TAESALDOCompleted As TAESALDOCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/atencion", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function atencion(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("atencion", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub atencionAsync(ByVal cadena As String)
            Me.atencionAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub atencionAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.atencionOperationCompleted Is Nothing) Then
                Me.atencionOperationCompleted = AddressOf Me.OnatencionOperationCompleted
            End If
            Me.InvokeAsync("atencion", New Object() {cadena}, Me.atencionOperationCompleted, userState)
        End Sub
        
        Private Sub OnatencionOperationCompleted(ByVal arg As Object)
            If (Not (Me.atencionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent atencionCompleted(Me, New atencionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/depositos", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function depositos(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("depositos", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub depositosAsync(ByVal cadena As String)
            Me.depositosAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub depositosAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.depositosOperationCompleted Is Nothing) Then
                Me.depositosOperationCompleted = AddressOf Me.OndepositosOperationCompleted
            End If
            Me.InvokeAsync("depositos", New Object() {cadena}, Me.depositosOperationCompleted, userState)
        End Sub
        
        Private Sub OndepositosOperationCompleted(ByVal arg As Object)
            If (Not (Me.depositosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent depositosCompleted(Me, New depositosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/moviaj", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function moviaj(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("moviaj", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub moviajAsync(ByVal cadena As String)
            Me.moviajAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub moviajAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.moviajOperationCompleted Is Nothing) Then
                Me.moviajOperationCompleted = AddressOf Me.OnmoviajOperationCompleted
            End If
            Me.InvokeAsync("moviaj", New Object() {cadena}, Me.moviajOperationCompleted, userState)
        End Sub
        
        Private Sub OnmoviajOperationCompleted(ByVal arg As Object)
            If (Not (Me.moviajCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent moviajCompleted(Me, New moviajCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/movidj", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function movidj(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("movidj", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub movidjAsync(ByVal cadena As String)
            Me.movidjAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub movidjAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.movidjOperationCompleted Is Nothing) Then
                Me.movidjOperationCompleted = AddressOf Me.OnmovidjOperationCompleted
            End If
            Me.InvokeAsync("movidj", New Object() {cadena}, Me.movidjOperationCompleted, userState)
        End Sub
        
        Private Sub OnmovidjOperationCompleted(ByVal arg As Object)
            If (Not (Me.movidjCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent movidjCompleted(Me, New movidjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/msnc", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function msnc(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("msnc", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub msncAsync(ByVal cadena As String)
            Me.msncAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub msncAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.msncOperationCompleted Is Nothing) Then
                Me.msncOperationCompleted = AddressOf Me.OnmsncOperationCompleted
            End If
            Me.InvokeAsync("msnc", New Object() {cadena}, Me.msncOperationCompleted, userState)
        End Sub
        
        Private Sub OnmsncOperationCompleted(ByVal arg As Object)
            If (Not (Me.msncCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent msncCompleted(Me, New msncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/msnldo", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function msnldo(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("msnldo", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub msnldoAsync(ByVal cadena As String)
            Me.msnldoAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub msnldoAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.msnldoOperationCompleted Is Nothing) Then
                Me.msnldoOperationCompleted = AddressOf Me.OnmsnldoOperationCompleted
            End If
            Me.InvokeAsync("msnldo", New Object() {cadena}, Me.msnldoOperationCompleted, userState)
        End Sub
        
        Private Sub OnmsnldoOperationCompleted(ByVal arg As Object)
            If (Not (Me.msnldoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent msnldoCompleted(Me, New msnldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/msn", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function msn(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("msn", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub msnAsync(ByVal cadena As String)
            Me.msnAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub msnAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.msnOperationCompleted Is Nothing) Then
                Me.msnOperationCompleted = AddressOf Me.OnmsnOperationCompleted
            End If
            Me.InvokeAsync("msn", New Object() {cadena}, Me.msnOperationCompleted, userState)
        End Sub
        
        Private Sub OnmsnOperationCompleted(ByVal arg As Object)
            If (Not (Me.msnCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent msnCompleted(Me, New msnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/movidrj", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function movidrj(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("movidrj", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub movidrjAsync(ByVal cadena As String)
            Me.movidrjAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub movidrjAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.movidrjOperationCompleted Is Nothing) Then
                Me.movidrjOperationCompleted = AddressOf Me.OnmovidrjOperationCompleted
            End If
            Me.InvokeAsync("movidrj", New Object() {cadena}, Me.movidrjOperationCompleted, userState)
        End Sub
        
        Private Sub OnmovidrjOperationCompleted(ByVal arg As Object)
            If (Not (Me.movidrjCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent movidrjCompleted(Me, New movidrjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/saldoj", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function saldoj(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("saldoj", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub saldojAsync(ByVal cadena As String)
            Me.saldojAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub saldojAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.saldojOperationCompleted Is Nothing) Then
                Me.saldojOperationCompleted = AddressOf Me.OnsaldojOperationCompleted
            End If
            Me.InvokeAsync("saldoj", New Object() {cadena}, Me.saldojOperationCompleted, userState)
        End Sub
        
        Private Sub OnsaldojOperationCompleted(ByVal arg As Object)
            If (Not (Me.saldojCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent saldojCompleted(Me, New saldojCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/java", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function java(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("java", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub javaAsync(ByVal cadena As String)
            Me.javaAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub javaAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.javaOperationCompleted Is Nothing) Then
                Me.javaOperationCompleted = AddressOf Me.OnjavaOperationCompleted
            End If
            Me.InvokeAsync("java", New Object() {cadena}, Me.javaOperationCompleted, userState)
        End Sub
        
        Private Sub OnjavaOperationCompleted(ByVal arg As Object)
            If (Not (Me.javaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent javaCompleted(Me, New javaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/gprstae", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function gprstae(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("gprstae", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub gprstaeAsync(ByVal cadena As String)
            Me.gprstaeAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub gprstaeAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.gprstaeOperationCompleted Is Nothing) Then
                Me.gprstaeOperationCompleted = AddressOf Me.OngprstaeOperationCompleted
            End If
            Me.InvokeAsync("gprstae", New Object() {cadena}, Me.gprstaeOperationCompleted, userState)
        End Sub
        
        Private Sub OngprstaeOperationCompleted(ByVal arg As Object)
            If (Not (Me.gprstaeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent gprstaeCompleted(Me, New gprstaeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/gprsaut", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function gprsaut(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("gprsaut", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub gprsautAsync(ByVal cadena As String)
            Me.gprsautAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub gprsautAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.gprsautOperationCompleted Is Nothing) Then
                Me.gprsautOperationCompleted = AddressOf Me.OngprsautOperationCompleted
            End If
            Me.InvokeAsync("gprsaut", New Object() {cadena}, Me.gprsautOperationCompleted, userState)
        End Sub
        
        Private Sub OngprsautOperationCompleted(ByVal arg As Object)
            If (Not (Me.gprsautCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent gprsautCompleted(Me, New gprsautCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/movij", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function movij(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("movij", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub movijAsync(ByVal cadena As String)
            Me.movijAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub movijAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.movijOperationCompleted Is Nothing) Then
                Me.movijOperationCompleted = AddressOf Me.OnmovijOperationCompleted
            End If
            Me.InvokeAsync("movij", New Object() {cadena}, Me.movijOperationCompleted, userState)
        End Sub
        
        Private Sub OnmovijOperationCompleted(ByVal arg As Object)
            If (Not (Me.movijCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent movijCompleted(Me, New movijCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/plugtae", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function plugtae(ByVal cadena As String) As String
            Dim results() As Object = Me.Invoke("plugtae", New Object() {cadena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub plugtaeAsync(ByVal cadena As String)
            Me.plugtaeAsync(cadena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub plugtaeAsync(ByVal cadena As String, ByVal userState As Object)
            If (Me.plugtaeOperationCompleted Is Nothing) Then
                Me.plugtaeOperationCompleted = AddressOf Me.OnplugtaeOperationCompleted
            End If
            Me.InvokeAsync("plugtae", New Object() {cadena}, Me.plugtaeOperationCompleted, userState)
        End Sub
        
        Private Sub OnplugtaeOperationCompleted(ByVal arg As Object)
            If (Not (Me.plugtaeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent plugtaeCompleted(Me, New plugtaeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/TAE", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TAE(ByVal usuario As String, ByVal password As String, ByVal producto As String, ByVal telefono As String, ByVal monto As String, ByVal puntov As String) As String
            Dim results() As Object = Me.Invoke("TAE", New Object() {usuario, password, producto, telefono, monto, puntov})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TAEAsync(ByVal usuario As String, ByVal password As String, ByVal producto As String, ByVal telefono As String, ByVal monto As String, ByVal puntov As String)
            Me.TAEAsync(usuario, password, producto, telefono, monto, puntov, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TAEAsync(ByVal usuario As String, ByVal password As String, ByVal producto As String, ByVal telefono As String, ByVal monto As String, ByVal puntov As String, ByVal userState As Object)
            If (Me.TAEOperationCompleted Is Nothing) Then
                Me.TAEOperationCompleted = AddressOf Me.OnTAEOperationCompleted
            End If
            Me.InvokeAsync("TAE", New Object() {usuario, password, producto, telefono, monto, puntov}, Me.TAEOperationCompleted, userState)
        End Sub
        
        Private Sub OnTAEOperationCompleted(ByVal arg As Object)
            If (Not (Me.TAECompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TAECompleted(Me, New TAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DMM/TAESALDO", RequestNamespace:="DMM", ResponseNamespace:="DMM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TAESALDO(ByVal usuario As String, ByVal password As String) As String
            Dim results() As Object = Me.Invoke("TAESALDO", New Object() {usuario, password})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TAESALDOAsync(ByVal usuario As String, ByVal password As String)
            Me.TAESALDOAsync(usuario, password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TAESALDOAsync(ByVal usuario As String, ByVal password As String, ByVal userState As Object)
            If (Me.TAESALDOOperationCompleted Is Nothing) Then
                Me.TAESALDOOperationCompleted = AddressOf Me.OnTAESALDOOperationCompleted
            End If
            Me.InvokeAsync("TAESALDO", New Object() {usuario, password}, Me.TAESALDOOperationCompleted, userState)
        End Sub
        
        Private Sub OnTAESALDOOperationCompleted(ByVal arg As Object)
            If (Not (Me.TAESALDOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TAESALDOCompleted(Me, New TAESALDOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub atencionCompletedEventHandler(ByVal sender As Object, ByVal e As atencionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class atencionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub depositosCompletedEventHandler(ByVal sender As Object, ByVal e As depositosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class depositosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub moviajCompletedEventHandler(ByVal sender As Object, ByVal e As moviajCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class moviajCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub movidjCompletedEventHandler(ByVal sender As Object, ByVal e As movidjCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class movidjCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub msncCompletedEventHandler(ByVal sender As Object, ByVal e As msncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class msncCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub msnldoCompletedEventHandler(ByVal sender As Object, ByVal e As msnldoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class msnldoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub msnCompletedEventHandler(ByVal sender As Object, ByVal e As msnCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class msnCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub movidrjCompletedEventHandler(ByVal sender As Object, ByVal e As movidrjCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class movidrjCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub saldojCompletedEventHandler(ByVal sender As Object, ByVal e As saldojCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class saldojCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub javaCompletedEventHandler(ByVal sender As Object, ByVal e As javaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class javaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub gprstaeCompletedEventHandler(ByVal sender As Object, ByVal e As gprstaeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class gprstaeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub gprsautCompletedEventHandler(ByVal sender As Object, ByVal e As gprsautCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class gprsautCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub movijCompletedEventHandler(ByVal sender As Object, ByVal e As movijCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class movijCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub plugtaeCompletedEventHandler(ByVal sender As Object, ByVal e As plugtaeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class plugtaeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub TAECompletedEventHandler(ByVal sender As Object, ByVal e As TAECompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TAECompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub TAESALDOCompletedEventHandler(ByVal sender As Object, ByVal e As TAESALDOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TAESALDOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
