//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackCode.ProntipagosClientService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siveta.ws.com")]
    public partial class WebServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(transactionResponseTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.usa.siveta.cm.com/")]
    public abstract partial class dto : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.usa.siveta.cm.com/")]
    public partial class transactionResponseTO : dto {
        
        private string codeTransactionField;
        
        private string statusTransactionField;
        
        private string codeDescriptionField;
        
        private string dateTransactionField;
        
        private string transactionIdField;
        
        private string folioTransactionField;
        
        private string transactionStatusDescriptionField;
        
        private string additionalInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codeTransaction {
            get {
                return this.codeTransactionField;
            }
            set {
                this.codeTransactionField = value;
                this.RaisePropertyChanged("codeTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusTransaction {
            get {
                return this.statusTransactionField;
            }
            set {
                this.statusTransactionField = value;
                this.RaisePropertyChanged("statusTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codeDescription {
            get {
                return this.codeDescriptionField;
            }
            set {
                this.codeDescriptionField = value;
                this.RaisePropertyChanged("codeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dateTransaction {
            get {
                return this.dateTransactionField;
            }
            set {
                this.dateTransactionField = value;
                this.RaisePropertyChanged("dateTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string folioTransaction {
            get {
                return this.folioTransactionField;
            }
            set {
                this.folioTransactionField = value;
                this.RaisePropertyChanged("folioTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string transactionStatusDescription {
            get {
                return this.transactionStatusDescriptionField;
            }
            set {
                this.transactionStatusDescriptionField = value;
                this.RaisePropertyChanged("transactionStatusDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string additionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
                this.RaisePropertyChanged("additionalInfo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siveta.ws.com")]
    public partial class TransactionException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.usa.siveta.cm.com/")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.usa.siveta.cm.com/", ConfigurationName="ProntipagosClientService.ProntipagosClientServiceEndPoint")]
    public interface ProntipagosClientServiceEndPoint {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/checkStatusTopUpRequ" +
            "est", ReplyAction="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/checkStatusTopUpResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BackCode.ProntipagosClientService.WebServiceException), Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/checkStatusTopUp/Fau" +
            "lt/WebServiceException", Name="WebServiceException")]
        [System.ServiceModel.FaultContractAttribute(typeof(BackCode.ProntipagosClientService.TransactionException), Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/checkStatusTopUp/Fau" +
            "lt/TransactionException", Name="TransactionException")]
        [System.ServiceModel.FaultContractAttribute(typeof(BackCode.ProntipagosClientService.ServiceException), Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/checkStatusTopUp/Fau" +
            "lt/ServiceException", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(dto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BackCode.ProntipagosClientService.checkStatusTopUpResponse checkStatusTopUp(BackCode.ProntipagosClientService.checkStatusTopUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/checkStatusTopUpRequ" +
            "est", ReplyAction="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/checkStatusTopUpResp" +
            "onse")]
        System.Threading.Tasks.Task<BackCode.ProntipagosClientService.checkStatusTopUpResponse> checkStatusTopUpAsync(BackCode.ProntipagosClientService.checkStatusTopUpRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpPackageRequest", ReplyAction="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpPackageResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(dto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BackCode.ProntipagosClientService.topUpPackageResponse topUpPackage(BackCode.ProntipagosClientService.topUpPackageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpPackageRequest", ReplyAction="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpPackageResponse" +
            "")]
        System.Threading.Tasks.Task<BackCode.ProntipagosClientService.topUpPackageResponse> topUpPackageAsync(BackCode.ProntipagosClientService.topUpPackageRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpTAERequest", ReplyAction="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpTAEResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BackCode.ProntipagosClientService.TransactionException), Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpTAE/Fault/Trans" +
            "actionException", Name="TransactionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(dto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BackCode.ProntipagosClientService.topUpTAEResponse topUpTAE(BackCode.ProntipagosClientService.topUpTAERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpTAERequest", ReplyAction="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpTAEResponse")]
        System.Threading.Tasks.Task<BackCode.ProntipagosClientService.topUpTAEResponse> topUpTAEAsync(BackCode.ProntipagosClientService.topUpTAERequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpRequest", ReplyAction="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(dto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BackCode.ProntipagosClientService.topUpResponse topUp(BackCode.ProntipagosClientService.topUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpRequest", ReplyAction="http://ws.usa.siveta.cm.com/ProntipagosClientServiceEndPoint/topUpResponse")]
        System.Threading.Tasks.Task<BackCode.ProntipagosClientService.topUpResponse> topUpAsync(BackCode.ProntipagosClientService.topUpRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkStatusTopUp", WrapperNamespace="http://ws.usa.siveta.cm.com/", IsWrapped=true)]
    public partial class checkStatusTopUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientReference;
        
        public checkStatusTopUpRequest() {
        }
        
        public checkStatusTopUpRequest(string clientReference) {
            this.clientReference = clientReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkStatusTopUpResponse", WrapperNamespace="http://ws.usa.siveta.cm.com/", IsWrapped=true)]
    public partial class checkStatusTopUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BackCode.ProntipagosClientService.transactionResponseTO @return;
        
        public checkStatusTopUpResponse() {
        }
        
        public checkStatusTopUpResponse(BackCode.ProntipagosClientService.transactionResponseTO @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.usa.siveta.cm.com/")]
    public partial class sellResponseTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private transactionResponseCode transactionCodeField;
        
        private bool transactionCodeFieldSpecified;
        
        private int transactionStatusField;
        
        private System.DateTime transactionDateField;
        
        private bool transactionDateFieldSpecified;
        
        private long transactionIdField;
        
        private bool transactionIdFieldSpecified;
        
        private string transactionFolioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public transactionResponseCode transactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
                this.RaisePropertyChanged("transactionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionCodeSpecified {
            get {
                return this.transactionCodeFieldSpecified;
            }
            set {
                this.transactionCodeFieldSpecified = value;
                this.RaisePropertyChanged("transactionCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
                this.RaisePropertyChanged("transactionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionDateSpecified {
            get {
                return this.transactionDateFieldSpecified;
            }
            set {
                this.transactionDateFieldSpecified = value;
                this.RaisePropertyChanged("transactionDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionIdSpecified {
            get {
                return this.transactionIdFieldSpecified;
            }
            set {
                this.transactionIdFieldSpecified = value;
                this.RaisePropertyChanged("transactionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string transactionFolio {
            get {
                return this.transactionFolioField;
            }
            set {
                this.transactionFolioField = value;
                this.RaisePropertyChanged("transactionFolio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.usa.siveta.cm.com/")]
    public enum transactionResponseCode {
        
        /// <remarks/>
        SUCCESSFUL_TX,
        
        /// <remarks/>
        INVALID_PHONE,
        
        /// <remarks/>
        DESTINATION_UNAVAILABLE,
        
        /// <remarks/>
        INVALID_AMOUNT,
        
        /// <remarks/>
        CANNOT_PROCESS_PHONE,
        
        /// <remarks/>
        UNAVAILABLE_CREDIT,
        
        /// <remarks/>
        TELCEL_MAINTENANCE,
        
        /// <remarks/>
        TX_TABLE_FULL,
        
        /// <remarks/>
        INTERNAL_TIMEOUT,
        
        /// <remarks/>
        UNAVAILABLE_AUTHORIZATOR,
        
        /// <remarks/>
        UNAVAILABLE_PRODUCT,
        
        /// <remarks/>
        NO_ACCOUNT_ASSOCIATED,
        
        /// <remarks/>
        NOT_AUTHORIZED_TO_SELL,
        
        /// <remarks/>
        INVALID_TICKET,
        
        /// <remarks/>
        SYSTEM_MAINTENANCE,
        
        /// <remarks/>
        AREA_CODE_NOT_ASSIGNED,
        
        /// <remarks/>
        TX_TIMEOUT,
        
        /// <remarks/>
        INSUFFICIENT_DATA,
        
        /// <remarks/>
        TX_INVALID_TRXID,
        
        /// <remarks/>
        INVALID_MSISDN,
        
        /// <remarks/>
        INVALID_KEYWORD,
        
        /// <remarks/>
        INVALID_USER,
        
        /// <remarks/>
        NOT_ALLOW_USER,
        
        /// <remarks/>
        MORE_THAN_ONE_SKU,
        
        /// <remarks/>
        ERROR_SELL,
        
        /// <remarks/>
        ERROR_WS,
        
        /// <remarks/>
        ERROR_HTTP_SESSION,
        
        /// <remarks/>
        PROCESSING_TRANSACTION,
        
        /// <remarks/>
        INVALID_SOURCE_ACCOUNT,
        
        /// <remarks/>
        INVALID_DESTINATION_ACCOUNT,
        
        /// <remarks/>
        INVALID_MAIL,
        
        /// <remarks/>
        NOT_ALLOWED_NODE_TYPE,
        
        /// <remarks/>
        UPDATE_SUCCESS,
        
        /// <remarks/>
        DUPLICATE_NODE_OR_USER,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="topUpPackage", WrapperNamespace="http://ws.usa.siveta.cm.com/", IsWrapped=true)]
    public partial class topUpPackageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sku;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientReference;
        
        public topUpPackageRequest() {
        }
        
        public topUpPackageRequest(double amount, string reference, string sku, string clientReference) {
            this.amount = amount;
            this.reference = reference;
            this.sku = sku;
            this.clientReference = clientReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="topUpPackageResponse", WrapperNamespace="http://ws.usa.siveta.cm.com/", IsWrapped=true)]
    public partial class topUpPackageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BackCode.ProntipagosClientService.sellResponseTO @return;
        
        public topUpPackageResponse() {
        }
        
        public topUpPackageResponse(BackCode.ProntipagosClientService.sellResponseTO @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.usa.siveta.cm.com/")]
    public partial class transactionResponseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeDescriptionField;
        
        private string codeTransactionField;
        
        private string dateTransactionField;
        
        private string folioTransactionField;
        
        private string statusTransactionField;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codeDescription {
            get {
                return this.codeDescriptionField;
            }
            set {
                this.codeDescriptionField = value;
                this.RaisePropertyChanged("codeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codeTransaction {
            get {
                return this.codeTransactionField;
            }
            set {
                this.codeTransactionField = value;
                this.RaisePropertyChanged("codeTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dateTransaction {
            get {
                return this.dateTransactionField;
            }
            set {
                this.dateTransactionField = value;
                this.RaisePropertyChanged("dateTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string folioTransaction {
            get {
                return this.folioTransactionField;
            }
            set {
                this.folioTransactionField = value;
                this.RaisePropertyChanged("folioTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string statusTransaction {
            get {
                return this.statusTransactionField;
            }
            set {
                this.statusTransactionField = value;
                this.RaisePropertyChanged("statusTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="topUpTAE", WrapperNamespace="http://ws.usa.siveta.cm.com/", IsWrapped=true)]
    public partial class topUpTAERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long msisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientReference;
        
        public topUpTAERequest() {
        }
        
        public topUpTAERequest(double amount, long msisdn, string clientReference) {
            this.amount = amount;
            this.msisdn = msisdn;
            this.clientReference = clientReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="topUpTAEResponse", WrapperNamespace="http://ws.usa.siveta.cm.com/", IsWrapped=true)]
    public partial class topUpTAEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BackCode.ProntipagosClientService.transactionResponseDto @return;
        
        public topUpTAEResponse() {
        }
        
        public topUpTAEResponse(BackCode.ProntipagosClientService.transactionResponseDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="topUp", WrapperNamespace="http://ws.usa.siveta.cm.com/", IsWrapped=true)]
    public partial class topUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sku;
        
        public topUpRequest() {
        }
        
        public topUpRequest(double amount, string reference, string clientReference, string sku) {
            this.amount = amount;
            this.reference = reference;
            this.clientReference = clientReference;
            this.sku = sku;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="topUpResponse", WrapperNamespace="http://ws.usa.siveta.cm.com/", IsWrapped=true)]
    public partial class topUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.usa.siveta.cm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BackCode.ProntipagosClientService.sellResponseTO @return;
        
        public topUpResponse() {
        }
        
        public topUpResponse(BackCode.ProntipagosClientService.sellResponseTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProntipagosClientServiceEndPointChannel : BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProntipagosClientServiceEndPointClient : System.ServiceModel.ClientBase<BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint>, BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint {
        
        public ProntipagosClientServiceEndPointClient() {
        }
        
        public ProntipagosClientServiceEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProntipagosClientServiceEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProntipagosClientServiceEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProntipagosClientServiceEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BackCode.ProntipagosClientService.checkStatusTopUpResponse BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint.checkStatusTopUp(BackCode.ProntipagosClientService.checkStatusTopUpRequest request) {
            return base.Channel.checkStatusTopUp(request);
        }
        
        public BackCode.ProntipagosClientService.transactionResponseTO checkStatusTopUp(string clientReference) {
            BackCode.ProntipagosClientService.checkStatusTopUpRequest inValue = new BackCode.ProntipagosClientService.checkStatusTopUpRequest();
            inValue.clientReference = clientReference;
            BackCode.ProntipagosClientService.checkStatusTopUpResponse retVal = ((BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint)(this)).checkStatusTopUp(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BackCode.ProntipagosClientService.checkStatusTopUpResponse> BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint.checkStatusTopUpAsync(BackCode.ProntipagosClientService.checkStatusTopUpRequest request) {
            return base.Channel.checkStatusTopUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<BackCode.ProntipagosClientService.checkStatusTopUpResponse> checkStatusTopUpAsync(string clientReference) {
            BackCode.ProntipagosClientService.checkStatusTopUpRequest inValue = new BackCode.ProntipagosClientService.checkStatusTopUpRequest();
            inValue.clientReference = clientReference;
            return ((BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint)(this)).checkStatusTopUpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BackCode.ProntipagosClientService.topUpPackageResponse BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint.topUpPackage(BackCode.ProntipagosClientService.topUpPackageRequest request) {
            return base.Channel.topUpPackage(request);
        }
        
        public BackCode.ProntipagosClientService.sellResponseTO topUpPackage(double amount, string reference, string sku, string clientReference) {
            BackCode.ProntipagosClientService.topUpPackageRequest inValue = new BackCode.ProntipagosClientService.topUpPackageRequest();
            inValue.amount = amount;
            inValue.reference = reference;
            inValue.sku = sku;
            inValue.clientReference = clientReference;
            BackCode.ProntipagosClientService.topUpPackageResponse retVal = ((BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint)(this)).topUpPackage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BackCode.ProntipagosClientService.topUpPackageResponse> BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint.topUpPackageAsync(BackCode.ProntipagosClientService.topUpPackageRequest request) {
            return base.Channel.topUpPackageAsync(request);
        }
        
        public System.Threading.Tasks.Task<BackCode.ProntipagosClientService.topUpPackageResponse> topUpPackageAsync(double amount, string reference, string sku, string clientReference) {
            BackCode.ProntipagosClientService.topUpPackageRequest inValue = new BackCode.ProntipagosClientService.topUpPackageRequest();
            inValue.amount = amount;
            inValue.reference = reference;
            inValue.sku = sku;
            inValue.clientReference = clientReference;
            return ((BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint)(this)).topUpPackageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BackCode.ProntipagosClientService.topUpTAEResponse BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint.topUpTAE(BackCode.ProntipagosClientService.topUpTAERequest request) {
            return base.Channel.topUpTAE(request);
        }
        
        public BackCode.ProntipagosClientService.transactionResponseDto topUpTAE(double amount, long msisdn, string clientReference) {
            BackCode.ProntipagosClientService.topUpTAERequest inValue = new BackCode.ProntipagosClientService.topUpTAERequest();
            inValue.amount = amount;
            inValue.msisdn = msisdn;
            inValue.clientReference = clientReference;
            BackCode.ProntipagosClientService.topUpTAEResponse retVal = ((BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint)(this)).topUpTAE(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BackCode.ProntipagosClientService.topUpTAEResponse> BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint.topUpTAEAsync(BackCode.ProntipagosClientService.topUpTAERequest request) {
            return base.Channel.topUpTAEAsync(request);
        }
        
        public System.Threading.Tasks.Task<BackCode.ProntipagosClientService.topUpTAEResponse> topUpTAEAsync(double amount, long msisdn, string clientReference) {
            BackCode.ProntipagosClientService.topUpTAERequest inValue = new BackCode.ProntipagosClientService.topUpTAERequest();
            inValue.amount = amount;
            inValue.msisdn = msisdn;
            inValue.clientReference = clientReference;
            return ((BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint)(this)).topUpTAEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BackCode.ProntipagosClientService.topUpResponse BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint.topUp(BackCode.ProntipagosClientService.topUpRequest request) {
            return base.Channel.topUp(request);
        }
        
        public BackCode.ProntipagosClientService.sellResponseTO topUp(double amount, string reference, string clientReference, string sku) {
            BackCode.ProntipagosClientService.topUpRequest inValue = new BackCode.ProntipagosClientService.topUpRequest();
            inValue.amount = amount;
            inValue.reference = reference;
            inValue.clientReference = clientReference;
            inValue.sku = sku;
            BackCode.ProntipagosClientService.topUpResponse retVal = ((BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint)(this)).topUp(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BackCode.ProntipagosClientService.topUpResponse> BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint.topUpAsync(BackCode.ProntipagosClientService.topUpRequest request) {
            return base.Channel.topUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<BackCode.ProntipagosClientService.topUpResponse> topUpAsync(double amount, string reference, string clientReference, string sku) {
            BackCode.ProntipagosClientService.topUpRequest inValue = new BackCode.ProntipagosClientService.topUpRequest();
            inValue.amount = amount;
            inValue.reference = reference;
            inValue.clientReference = clientReference;
            inValue.sku = sku;
            return ((BackCode.ProntipagosClientService.ProntipagosClientServiceEndPoint)(this)).topUpAsync(inValue);
        }
    }
}
