'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace TerriaService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://webservices/", ConfigurationName:="TerriaService.Service")>  _
    Public Interface Service
        
        'CODEGEN: Generating message contract since element name ticket from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/aliveRequest", ReplyAction:="http://webservices/Service/aliveResponse")>  _
        Function alive(ByVal request As TerriaService.aliveRequest) As TerriaService.aliveResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/aliveRequest", ReplyAction:="http://webservices/Service/aliveResponse")>  _
        Function aliveAsync(ByVal request As TerriaService.aliveRequest) As System.Threading.Tasks.Task(Of TerriaService.aliveResponse)
        
        'CODEGEN: Generating message contract since element name ticket from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/getProductsRequest", ReplyAction:="http://webservices/Service/getProductsResponse")>  _
        Function getProducts(ByVal request As TerriaService.getProductsRequest) As TerriaService.getProductsResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/getProductsRequest", ReplyAction:="http://webservices/Service/getProductsResponse")>  _
        Function getProductsAsync(ByVal request As TerriaService.getProductsRequest) As System.Threading.Tasks.Task(Of TerriaService.getProductsResponse)
        
        'CODEGEN: Generating message contract since element name ticket from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/getProducts2Request", ReplyAction:="http://webservices/Service/getProducts2Response")>  _
        Function getProducts2(ByVal request As TerriaService.getProducts2Request) As TerriaService.getProducts2Response
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/getProducts2Request", ReplyAction:="http://webservices/Service/getProducts2Response")>  _
        Function getProducts2Async(ByVal request As TerriaService.getProducts2Request) As System.Threading.Tasks.Task(Of TerriaService.getProducts2Response)
        
        'CODEGEN: Generating message contract since element name ticket from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/responseTelcelRequest", ReplyAction:="http://webservices/Service/responseTelcelResponse")>  _
        Function responseTelcel(ByVal request As TerriaService.responseTelcelRequest) As TerriaService.responseTelcelResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/responseTelcelRequest", ReplyAction:="http://webservices/Service/responseTelcelResponse")>  _
        Function responseTelcelAsync(ByVal request As TerriaService.responseTelcelRequest) As System.Threading.Tasks.Task(Of TerriaService.responseTelcelResponse)
        
        'CODEGEN: Generating message contract since element name ticket from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/changePasswordRequest", ReplyAction:="http://webservices/Service/changePasswordResponse")>  _
        Function changePassword(ByVal request As TerriaService.changePasswordRequest) As TerriaService.changePasswordResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/changePasswordRequest", ReplyAction:="http://webservices/Service/changePasswordResponse")>  _
        Function changePasswordAsync(ByVal request As TerriaService.changePasswordRequest) As System.Threading.Tasks.Task(Of TerriaService.changePasswordResponse)
        
        'CODEGEN: Generating message contract since element name ticket from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/balanceRequestRequest", ReplyAction:="http://webservices/Service/balanceRequestResponse")>  _
        Function balanceRequest(ByVal request As TerriaService.balanceRequestRequest) As TerriaService.balanceRequestResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/balanceRequestRequest", ReplyAction:="http://webservices/Service/balanceRequestResponse")>  _
        Function balanceRequestAsync(ByVal request As TerriaService.balanceRequestRequest) As System.Threading.Tasks.Task(Of TerriaService.balanceRequestResponse)
        
        'CODEGEN: Generating message contract since element name ticket from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/saleRequestRequest", ReplyAction:="http://webservices/Service/saleRequestResponse")>  _
        Function saleRequest(ByVal request As TerriaService.saleRequestRequest) As TerriaService.saleRequestResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/saleRequestRequest", ReplyAction:="http://webservices/Service/saleRequestResponse")>  _
        Function saleRequestAsync(ByVal request As TerriaService.saleRequestRequest) As System.Threading.Tasks.Task(Of TerriaService.saleRequestResponse)
        
        'CODEGEN: Generating message contract since element name ticket from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/saleCheckRequest", ReplyAction:="http://webservices/Service/saleCheckResponse")>  _
        Function saleCheck(ByVal request As TerriaService.saleCheckRequest) As TerriaService.saleCheckResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/saleCheckRequest", ReplyAction:="http://webservices/Service/saleCheckResponse")>  _
        Function saleCheckAsync(ByVal request As TerriaService.saleCheckRequest) As System.Threading.Tasks.Task(Of TerriaService.saleCheckResponse)
        
        'CODEGEN: Generating message contract since element name company from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/loginRequest", ReplyAction:="http://webservices/Service/loginResponse")>  _
        Function login(ByVal request As TerriaService.loginRequest) As TerriaService.loginResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/loginRequest", ReplyAction:="http://webservices/Service/loginResponse")>  _
        Function loginAsync(ByVal request As TerriaService.loginRequest) As System.Threading.Tasks.Task(Of TerriaService.loginResponse)
        
        'CODEGEN: Generating message contract since element name ticket from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/logoutRequest", ReplyAction:="http://webservices/Service/logoutResponse")>  _
        Function logout(ByVal request As TerriaService.logoutRequest) As TerriaService.logoutResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/logoutRequest", ReplyAction:="http://webservices/Service/logoutResponse")>  _
        Function logoutAsync(ByVal request As TerriaService.logoutRequest) As System.Threading.Tasks.Task(Of TerriaService.logoutResponse)
        
        'CODEGEN: Generating message contract since element name ticket from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/statusRequest", ReplyAction:="http://webservices/Service/statusResponse")>  _
        Function status(ByVal request As TerriaService.statusRequest) As TerriaService.statusResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservices/Service/statusRequest", ReplyAction:="http://webservices/Service/statusResponse")>  _
        Function statusAsync(ByVal request As TerriaService.statusRequest) As System.Threading.Tasks.Task(Of TerriaService.statusResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class aliveRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="alive", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.aliveRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.aliveRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class aliveRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ticket As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String)
            MyBase.New
            Me.ticket = ticket
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class aliveResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="aliveResponse", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.aliveResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.aliveResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class aliveResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getProductsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getProducts", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.getProductsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.getProductsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class getProductsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ticket As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String)
            MyBase.New
            Me.ticket = ticket
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getProductsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getProductsResponse", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.getProductsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.getProductsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class getProductsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getProducts2Request
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getProducts2", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.getProducts2RequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.getProducts2RequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class getProducts2RequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ticket As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String)
            MyBase.New
            Me.ticket = ticket
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getProducts2Response
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getProducts2Response", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.getProducts2ResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.getProducts2ResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class getProducts2ResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class responseTelcelRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="responseTelcel", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.responseTelcelRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.responseTelcelRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class responseTelcelRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ticket As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String)
            MyBase.New
            Me.ticket = ticket
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class responseTelcelResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="responseTelcelResponse", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.responseTelcelResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.responseTelcelResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class responseTelcelResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class changePasswordRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="changePassword", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.changePasswordRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.changePasswordRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class changePasswordRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ticket As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public company As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public user As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public password2 As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String, ByVal company As String, ByVal user As String, ByVal password As String, ByVal password2 As String)
            MyBase.New
            Me.ticket = ticket
            Me.company = company
            Me.user = user
            Me.password = password
            Me.password2 = password2
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class changePasswordResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="changePasswordResponse", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.changePasswordResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.changePasswordResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class changePasswordResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class balanceRequestRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="balanceRequest", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.balanceRequestRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.balanceRequestRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class balanceRequestRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ticket As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public companyId As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public storeId As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String, ByVal companyId As Integer, ByVal storeId As Integer)
            MyBase.New
            Me.ticket = ticket
            Me.companyId = companyId
            Me.storeId = storeId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class balanceRequestResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="balanceRequestResponse", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.balanceRequestResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.balanceRequestResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class balanceRequestResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saleRequestRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="saleRequest", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.saleRequestRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.saleRequestRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class saleRequestRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ticket As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public storeId As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public accountNo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public externalId As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public productId As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public phone As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public amount As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String, ByVal storeId As Integer, ByVal accountNo As String, ByVal externalId As String, ByVal productId As String, ByVal phone As String, ByVal amount As String)
            MyBase.New
            Me.ticket = ticket
            Me.storeId = storeId
            Me.accountNo = accountNo
            Me.externalId = externalId
            Me.productId = productId
            Me.phone = phone
            Me.amount = amount
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saleRequestResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="saleRequestResponse", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.saleRequestResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.saleRequestResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class saleRequestResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saleCheckRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="saleCheck", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.saleCheckRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.saleCheckRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class saleCheckRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ticket As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public externalId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String, ByVal externalId As String)
            MyBase.New
            Me.ticket = ticket
            Me.externalId = externalId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saleCheckResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="saleCheckResponse", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.saleCheckResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.saleCheckResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class saleCheckResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class loginRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="login", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.loginRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.loginRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class loginRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public company As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public userId As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public password As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal company As String, ByVal userId As String, ByVal password As String)
            MyBase.New
            Me.company = company
            Me.userId = userId
            Me.password = password
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class loginResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="loginResponse", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.loginResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.loginResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class loginResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class logoutRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="logout", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.logoutRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.logoutRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class logoutRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ticket As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String)
            MyBase.New
            Me.ticket = ticket
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class logoutResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="logoutResponse", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.logoutResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.logoutResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class logoutResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class statusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="status", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.statusRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.statusRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class statusRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ticket As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String)
            MyBase.New
            Me.ticket = ticket
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class statusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="statusResponse", [Namespace]:="http://webservices/", Order:=0)>  _
        Public Body As TerriaService.statusResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TerriaService.statusResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class statusResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceChannel
        Inherits TerriaService.Service, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceClient
        Inherits System.ServiceModel.ClientBase(Of TerriaService.Service)
        Implements TerriaService.Service
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_alive(ByVal request As TerriaService.aliveRequest) As TerriaService.aliveResponse Implements TerriaService.Service.alive
            Return MyBase.Channel.alive(request)
        End Function
        
        Public Function alive(ByVal ticket As String) As String
            Dim inValue As TerriaService.aliveRequest = New TerriaService.aliveRequest()
            inValue.Body = New TerriaService.aliveRequestBody()
            inValue.Body.ticket = ticket
            Dim retVal As TerriaService.aliveResponse = CType(Me,TerriaService.Service).alive(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_aliveAsync(ByVal request As TerriaService.aliveRequest) As System.Threading.Tasks.Task(Of TerriaService.aliveResponse) Implements TerriaService.Service.aliveAsync
            Return MyBase.Channel.aliveAsync(request)
        End Function
        
        Public Function aliveAsync(ByVal ticket As String) As System.Threading.Tasks.Task(Of TerriaService.aliveResponse)
            Dim inValue As TerriaService.aliveRequest = New TerriaService.aliveRequest()
            inValue.Body = New TerriaService.aliveRequestBody()
            inValue.Body.ticket = ticket
            Return CType(Me,TerriaService.Service).aliveAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_getProducts(ByVal request As TerriaService.getProductsRequest) As TerriaService.getProductsResponse Implements TerriaService.Service.getProducts
            Return MyBase.Channel.getProducts(request)
        End Function
        
        Public Function getProducts(ByVal ticket As String) As String
            Dim inValue As TerriaService.getProductsRequest = New TerriaService.getProductsRequest()
            inValue.Body = New TerriaService.getProductsRequestBody()
            inValue.Body.ticket = ticket
            Dim retVal As TerriaService.getProductsResponse = CType(Me,TerriaService.Service).getProducts(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_getProductsAsync(ByVal request As TerriaService.getProductsRequest) As System.Threading.Tasks.Task(Of TerriaService.getProductsResponse) Implements TerriaService.Service.getProductsAsync
            Return MyBase.Channel.getProductsAsync(request)
        End Function
        
        Public Function getProductsAsync(ByVal ticket As String) As System.Threading.Tasks.Task(Of TerriaService.getProductsResponse)
            Dim inValue As TerriaService.getProductsRequest = New TerriaService.getProductsRequest()
            inValue.Body = New TerriaService.getProductsRequestBody()
            inValue.Body.ticket = ticket
            Return CType(Me,TerriaService.Service).getProductsAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_getProducts2(ByVal request As TerriaService.getProducts2Request) As TerriaService.getProducts2Response Implements TerriaService.Service.getProducts2
            Return MyBase.Channel.getProducts2(request)
        End Function
        
        Public Function getProducts2(ByVal ticket As String) As String
            Dim inValue As TerriaService.getProducts2Request = New TerriaService.getProducts2Request()
            inValue.Body = New TerriaService.getProducts2RequestBody()
            inValue.Body.ticket = ticket
            Dim retVal As TerriaService.getProducts2Response = CType(Me,TerriaService.Service).getProducts2(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_getProducts2Async(ByVal request As TerriaService.getProducts2Request) As System.Threading.Tasks.Task(Of TerriaService.getProducts2Response) Implements TerriaService.Service.getProducts2Async
            Return MyBase.Channel.getProducts2Async(request)
        End Function
        
        Public Function getProducts2Async(ByVal ticket As String) As System.Threading.Tasks.Task(Of TerriaService.getProducts2Response)
            Dim inValue As TerriaService.getProducts2Request = New TerriaService.getProducts2Request()
            inValue.Body = New TerriaService.getProducts2RequestBody()
            inValue.Body.ticket = ticket
            Return CType(Me,TerriaService.Service).getProducts2Async(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_responseTelcel(ByVal request As TerriaService.responseTelcelRequest) As TerriaService.responseTelcelResponse Implements TerriaService.Service.responseTelcel
            Return MyBase.Channel.responseTelcel(request)
        End Function
        
        Public Function responseTelcel(ByVal ticket As String) As String
            Dim inValue As TerriaService.responseTelcelRequest = New TerriaService.responseTelcelRequest()
            inValue.Body = New TerriaService.responseTelcelRequestBody()
            inValue.Body.ticket = ticket
            Dim retVal As TerriaService.responseTelcelResponse = CType(Me,TerriaService.Service).responseTelcel(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_responseTelcelAsync(ByVal request As TerriaService.responseTelcelRequest) As System.Threading.Tasks.Task(Of TerriaService.responseTelcelResponse) Implements TerriaService.Service.responseTelcelAsync
            Return MyBase.Channel.responseTelcelAsync(request)
        End Function
        
        Public Function responseTelcelAsync(ByVal ticket As String) As System.Threading.Tasks.Task(Of TerriaService.responseTelcelResponse)
            Dim inValue As TerriaService.responseTelcelRequest = New TerriaService.responseTelcelRequest()
            inValue.Body = New TerriaService.responseTelcelRequestBody()
            inValue.Body.ticket = ticket
            Return CType(Me,TerriaService.Service).responseTelcelAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_changePassword(ByVal request As TerriaService.changePasswordRequest) As TerriaService.changePasswordResponse Implements TerriaService.Service.changePassword
            Return MyBase.Channel.changePassword(request)
        End Function
        
        Public Function changePassword(ByVal ticket As String, ByVal company As String, ByVal user As String, ByVal password As String, ByVal password2 As String) As String
            Dim inValue As TerriaService.changePasswordRequest = New TerriaService.changePasswordRequest()
            inValue.Body = New TerriaService.changePasswordRequestBody()
            inValue.Body.ticket = ticket
            inValue.Body.company = company
            inValue.Body.user = user
            inValue.Body.password = password
            inValue.Body.password2 = password2
            Dim retVal As TerriaService.changePasswordResponse = CType(Me,TerriaService.Service).changePassword(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_changePasswordAsync(ByVal request As TerriaService.changePasswordRequest) As System.Threading.Tasks.Task(Of TerriaService.changePasswordResponse) Implements TerriaService.Service.changePasswordAsync
            Return MyBase.Channel.changePasswordAsync(request)
        End Function
        
        Public Function changePasswordAsync(ByVal ticket As String, ByVal company As String, ByVal user As String, ByVal password As String, ByVal password2 As String) As System.Threading.Tasks.Task(Of TerriaService.changePasswordResponse)
            Dim inValue As TerriaService.changePasswordRequest = New TerriaService.changePasswordRequest()
            inValue.Body = New TerriaService.changePasswordRequestBody()
            inValue.Body.ticket = ticket
            inValue.Body.company = company
            inValue.Body.user = user
            inValue.Body.password = password
            inValue.Body.password2 = password2
            Return CType(Me,TerriaService.Service).changePasswordAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_balanceRequest(ByVal request As TerriaService.balanceRequestRequest) As TerriaService.balanceRequestResponse Implements TerriaService.Service.balanceRequest
            Return MyBase.Channel.balanceRequest(request)
        End Function
        
        Public Function balanceRequest(ByVal ticket As String, ByVal companyId As Integer, ByVal storeId As Integer) As String
            Dim inValue As TerriaService.balanceRequestRequest = New TerriaService.balanceRequestRequest()
            inValue.Body = New TerriaService.balanceRequestRequestBody()
            inValue.Body.ticket = ticket
            inValue.Body.companyId = companyId
            inValue.Body.storeId = storeId
            Dim retVal As TerriaService.balanceRequestResponse = CType(Me,TerriaService.Service).balanceRequest(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_balanceRequestAsync(ByVal request As TerriaService.balanceRequestRequest) As System.Threading.Tasks.Task(Of TerriaService.balanceRequestResponse) Implements TerriaService.Service.balanceRequestAsync
            Return MyBase.Channel.balanceRequestAsync(request)
        End Function
        
        Public Function balanceRequestAsync(ByVal ticket As String, ByVal companyId As Integer, ByVal storeId As Integer) As System.Threading.Tasks.Task(Of TerriaService.balanceRequestResponse)
            Dim inValue As TerriaService.balanceRequestRequest = New TerriaService.balanceRequestRequest()
            inValue.Body = New TerriaService.balanceRequestRequestBody()
            inValue.Body.ticket = ticket
            inValue.Body.companyId = companyId
            inValue.Body.storeId = storeId
            Return CType(Me,TerriaService.Service).balanceRequestAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_saleRequest(ByVal request As TerriaService.saleRequestRequest) As TerriaService.saleRequestResponse Implements TerriaService.Service.saleRequest
            Return MyBase.Channel.saleRequest(request)
        End Function
        
        Public Function saleRequest(ByVal ticket As String, ByVal storeId As Integer, ByVal accountNo As String, ByVal externalId As String, ByVal productId As String, ByVal phone As String, ByVal amount As String) As String
            Dim inValue As TerriaService.saleRequestRequest = New TerriaService.saleRequestRequest()
            inValue.Body = New TerriaService.saleRequestRequestBody()
            inValue.Body.ticket = ticket
            inValue.Body.storeId = storeId
            inValue.Body.accountNo = accountNo
            inValue.Body.externalId = externalId
            inValue.Body.productId = productId
            inValue.Body.phone = phone
            inValue.Body.amount = amount
            Dim retVal As TerriaService.saleRequestResponse = CType(Me,TerriaService.Service).saleRequest(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_saleRequestAsync(ByVal request As TerriaService.saleRequestRequest) As System.Threading.Tasks.Task(Of TerriaService.saleRequestResponse) Implements TerriaService.Service.saleRequestAsync
            Return MyBase.Channel.saleRequestAsync(request)
        End Function
        
        Public Function saleRequestAsync(ByVal ticket As String, ByVal storeId As Integer, ByVal accountNo As String, ByVal externalId As String, ByVal productId As String, ByVal phone As String, ByVal amount As String) As System.Threading.Tasks.Task(Of TerriaService.saleRequestResponse)
            Dim inValue As TerriaService.saleRequestRequest = New TerriaService.saleRequestRequest()
            inValue.Body = New TerriaService.saleRequestRequestBody()
            inValue.Body.ticket = ticket
            inValue.Body.storeId = storeId
            inValue.Body.accountNo = accountNo
            inValue.Body.externalId = externalId
            inValue.Body.productId = productId
            inValue.Body.phone = phone
            inValue.Body.amount = amount
            Return CType(Me,TerriaService.Service).saleRequestAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_saleCheck(ByVal request As TerriaService.saleCheckRequest) As TerriaService.saleCheckResponse Implements TerriaService.Service.saleCheck
            Return MyBase.Channel.saleCheck(request)
        End Function
        
        Public Function saleCheck(ByVal ticket As String, ByVal externalId As String) As String
            Dim inValue As TerriaService.saleCheckRequest = New TerriaService.saleCheckRequest()
            inValue.Body = New TerriaService.saleCheckRequestBody()
            inValue.Body.ticket = ticket
            inValue.Body.externalId = externalId
            Dim retVal As TerriaService.saleCheckResponse = CType(Me,TerriaService.Service).saleCheck(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_saleCheckAsync(ByVal request As TerriaService.saleCheckRequest) As System.Threading.Tasks.Task(Of TerriaService.saleCheckResponse) Implements TerriaService.Service.saleCheckAsync
            Return MyBase.Channel.saleCheckAsync(request)
        End Function
        
        Public Function saleCheckAsync(ByVal ticket As String, ByVal externalId As String) As System.Threading.Tasks.Task(Of TerriaService.saleCheckResponse)
            Dim inValue As TerriaService.saleCheckRequest = New TerriaService.saleCheckRequest()
            inValue.Body = New TerriaService.saleCheckRequestBody()
            inValue.Body.ticket = ticket
            inValue.Body.externalId = externalId
            Return CType(Me,TerriaService.Service).saleCheckAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_login(ByVal request As TerriaService.loginRequest) As TerriaService.loginResponse Implements TerriaService.Service.login
            Return MyBase.Channel.login(request)
        End Function
        
        Public Function login(ByVal company As String, ByVal userId As String, ByVal password As String) As String
            Dim inValue As TerriaService.loginRequest = New TerriaService.loginRequest()
            inValue.Body = New TerriaService.loginRequestBody()
            inValue.Body.company = company
            inValue.Body.userId = userId
            inValue.Body.password = password
            Dim retVal As TerriaService.loginResponse = CType(Me,TerriaService.Service).login(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_loginAsync(ByVal request As TerriaService.loginRequest) As System.Threading.Tasks.Task(Of TerriaService.loginResponse) Implements TerriaService.Service.loginAsync
            Return MyBase.Channel.loginAsync(request)
        End Function
        
        Public Function loginAsync(ByVal company As String, ByVal userId As String, ByVal password As String) As System.Threading.Tasks.Task(Of TerriaService.loginResponse)
            Dim inValue As TerriaService.loginRequest = New TerriaService.loginRequest()
            inValue.Body = New TerriaService.loginRequestBody()
            inValue.Body.company = company
            inValue.Body.userId = userId
            inValue.Body.password = password
            Return CType(Me,TerriaService.Service).loginAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_logout(ByVal request As TerriaService.logoutRequest) As TerriaService.logoutResponse Implements TerriaService.Service.logout
            Return MyBase.Channel.logout(request)
        End Function
        
        Public Sub logout(ByVal ticket As String)
            Dim inValue As TerriaService.logoutRequest = New TerriaService.logoutRequest()
            inValue.Body = New TerriaService.logoutRequestBody()
            inValue.Body.ticket = ticket
            Dim retVal As TerriaService.logoutResponse = CType(Me,TerriaService.Service).logout(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_logoutAsync(ByVal request As TerriaService.logoutRequest) As System.Threading.Tasks.Task(Of TerriaService.logoutResponse) Implements TerriaService.Service.logoutAsync
            Return MyBase.Channel.logoutAsync(request)
        End Function
        
        Public Function logoutAsync(ByVal ticket As String) As System.Threading.Tasks.Task(Of TerriaService.logoutResponse)
            Dim inValue As TerriaService.logoutRequest = New TerriaService.logoutRequest()
            inValue.Body = New TerriaService.logoutRequestBody()
            inValue.Body.ticket = ticket
            Return CType(Me,TerriaService.Service).logoutAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_status(ByVal request As TerriaService.statusRequest) As TerriaService.statusResponse Implements TerriaService.Service.status
            Return MyBase.Channel.status(request)
        End Function
        
        Public Function status(ByVal ticket As String) As String
            Dim inValue As TerriaService.statusRequest = New TerriaService.statusRequest()
            inValue.Body = New TerriaService.statusRequestBody()
            inValue.Body.ticket = ticket
            Dim retVal As TerriaService.statusResponse = CType(Me,TerriaService.Service).status(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TerriaService_Service_statusAsync(ByVal request As TerriaService.statusRequest) As System.Threading.Tasks.Task(Of TerriaService.statusResponse) Implements TerriaService.Service.statusAsync
            Return MyBase.Channel.statusAsync(request)
        End Function
        
        Public Function statusAsync(ByVal ticket As String) As System.Threading.Tasks.Task(Of TerriaService.statusResponse)
            Dim inValue As TerriaService.statusRequest = New TerriaService.statusRequest()
            inValue.Body = New TerriaService.statusRequestBody()
            inValue.Body.ticket = ticket
            Return CType(Me,TerriaService.Service).statusAsync(inValue)
        End Function
    End Class
End Namespace
